configfile: './config.yaml'

import itertools

all_cancers = config['cancers']
joined_cancers = '_'.join(config['cancers'])
requested_walk_amounts = range(3, config['classifier_max_walk_amounts'] + 1)
requested_walk_distance = range(3, config['classifier_max_walk_distance'] + 1)
distance_metrics = config['distance_metrics']
max_iterations = range(1, config['run_iterations'])

modalities = config['modalities']
modality_combinations = [
    "_".join(sorted(combo)) for r in range(2, len(modalities) + 1)
    for combo in itertools.combinations(modalities, r)
]

cancer_arg = ' '.join(all_cancers)

def modality_to_cli(modality_combo):
    return modality_combo.replace('_', ' ')


rule all:
    input:
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/overview_scores_heatmap_MCC.png",
            cancers=[joined_cancers],
            modalities=modality_combinations
        ),
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/clustering/{walk_distance}_{walk_amount}_gmm_clustering.png",
            cancers=[joined_cancers],
            modalities=modality_combinations,
            walk_distance=[requested_walk_distance[-1]],
            walk_amount=[requested_walk_amounts[-1]]
        ),
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/clustering/{walk_distance}_{walk_amount}_pca_clustering.png",
            cancers=[joined_cancers],
            modalities=modality_combinations,
            walk_distance=[requested_walk_distance[-1]],
            walk_amount=[requested_walk_amounts[-1]]
        ),

        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/accuracy_score_grid.png",
            cancers=[joined_cancers],
            modalities=modality_combinations
        ),
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/f1_score_grid.png",
            cancers=[joined_cancers],
            modalities=modality_combinations
        ),
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/f1_score.png",
            cancers=[joined_cancers],
            modalities=modality_combinations
        ),
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/accuracy_score.png",
            cancers=[joined_cancers],
            modalities=modality_combinations
        ),
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/{walk_distance}_{walk_amount}_confusion_matrix.png",
            cancers=[joined_cancers],
            modalities=modality_combinations,
            walk_distance=requested_walk_distance,
            walk_amount=requested_walk_amounts
        )

rule generate_gmm_plots:
    input:
        expand(
            "results/classifier_holdout/summed_embeddings/{cancers}/{modalities}/{walk_distance}_{walk_amount}/{iteration}/summed_embeddings.h5",
            cancers=[joined_cancers],
            modalities=modality_combinations,
            walk_amount=requested_walk_amounts,
            walk_distance=requested_walk_distance,
            iteration=max_iterations
        )
    output:
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/clustering/{walk_distance}_{walk_amount}_gmm_clustering.png",
            cancers=[joined_cancers],
            modalities=modality_combinations,
            walk_distance=[requested_walk_distance[-1]],
            walk_amount=[requested_walk_amounts[-1]]
        ),
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/clustering/{walk_distance}_{walk_amount}_pca_clustering.png",
            cancers=[joined_cancers],
            modalities=modality_combinations,
            walk_distance=[requested_walk_distance[-1]],
            walk_amount=[requested_walk_amounts[-1]]
        )
    run:
        for m in modality_combinations:
            m_cli = modality_to_cli(m)
            for walk_distance in requested_walk_distance:
                for walk in requested_walk_amounts:
                    shell(f"python3 src/classifier_holdout/plots/6_05_gmm_clustering.py -c {cancer_arg} -m {m_cli} -w {walk_distance} -a {walk}")


rule create_performance_plots:
    input:
        expand(
            "results/classifier_holdout/classification/{cancers}/{modalities}/{walk_distance}_{walk_amount}/{iteration}/results.csv",
            cancers=[joined_cancers],
            modalities=modality_combinations,
            walk_distance=requested_walk_distance,
            walk_amount=requested_walk_amounts,
            iteration=max_iterations
        )
    output:
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/accuracy_score_grid.png",
            cancers=[joined_cancers],
            modalities=modality_combinations
        ),
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/f1_score_grid.png",
            cancers=[joined_cancers],
            modalities=modality_combinations
        ),
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/overview_scores.png",
            cancers=[joined_cancers],
            modalities=modality_combinations
        ),
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/overview_scores_heatmap_MCC.png",
            cancers=[joined_cancers],
            modalities=modality_combinations
        ),
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/f1_score.png",
            cancers=[joined_cancers],
            modalities=modality_combinations
        ),
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/accuracy_score.png",
            cancers=[joined_cancers],
            modalities=modality_combinations
        )
    run:
        for m in modality_combinations:
            m_cli = modality_to_cli(m)
            shell(f"python3 src/classifier_holdout/plots/6_01_performance.py -c {cancer_arg} -m {m_cli}")


rule create_confusion_matrix:
    input:
        expand(
            "results/classifier_holdout/classification/{cancers}/{modalities}/{walk_distance}_{walk_amount}/{iteration}/predictions.csv",
            cancers=[joined_cancers],
            modalities=modality_combinations,
            walk_distance=requested_walk_distance,
            walk_amount=requested_walk_amounts,
            iteration=max_iterations
        )
    output:
        expand(
            "figures/classifier_holdout/{cancers}/{modalities}/performance/{walk_distance}_{walk_amount}_confusion_matrix.png",
            cancers=[joined_cancers],
            modalities=modality_combinations,
            walk_distance=requested_walk_distance,
            walk_amount=requested_walk_amounts
        )
    run:
        for m in modality_combinations:
            m_cli = modality_to_cli(m)
            for walk_distance in requested_walk_distance:
                for walk in requested_walk_amounts:
                    shell(f"python3 src/classifier_holdout/plots/6_04_confusion_matrix.py -c {cancer_arg} -m {m_cli} -w {walk_distance} -a {walk}")